apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoweb
spec:
  selector:
    matchLabels:
      app: demoweb
  template:
    metadata:
      labels:
        app: demoweb
    spec:
      containers:
        - env:
            - name: F5DEMO_APP
              value: website
            - name: F5DEMO_NODENAME
              value: 'F5 Digital Academy Volterra 101'
          image: >-
            chen23/f5-demo-httpd:openshift
          imagePullPolicy: IfNotPresent
          name: demoweb
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: demoweb
  creationTimestamp: null
  labels:
    app: demoweb
spec:
  ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: demoweb
status:
loadBalancer:
